### ISSUE TITLE
Question about Making the Data loaders

### ISSUE THREAD

**Issue by shaoniana1997** [atcbosselut/comet-commonsense#34]
Dear author :
        I follow the instruction in the Readme file,when i try to make the data loaders about conceptNet,i came across the question:
~/comet-commonsense$ python scripts/data/make_conceptnet_data_loader.py
100%███████████████████████████████████████████| 100000/100000 [04:06<00:00, 405.46it/s]
100%███████████████████████████████████████████████████| 2400/2400 [00:05<00:00, 408.77it/s]
100%|████████████████████████████████████| 2400/2400 [00:05<00:00, 426.74it/s]
28
16
16
dev
Traceback (most recent call last):
  File "scripts/data/make_conceptnet_data_loader.py", line 66, in <module>
    data_loader.make_tensors(text_encoder, special, test=False)
  File "/home/caihanqing/comet-commonsense/src/data/conceptnet.py", line 196, in make_tensors
    self.data[split]['total']) if not j[3]]))
RuntimeError: index out of range: Tried to access index 2306 out of table with 2305 rows. at /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
Can you give me some useful advice to my further training ? @madaan @atcbosselut

**Comment by shaoniana1997** [comment]
I have solved this problem .
